### ISSUE TITLE
switch to a better ctags for ruby as in rbenv-ctags

### ISSUE THREAD

**Issue by yangchenyun** [tpope/gem-ctags#10]
https://github.com/tpope/rbenv-ctags/issues/4

**Comment by ianks** [comment]
There is also [Starscope](https://github.com/eapache/starscope) which I would like to implement. I also agree with @tpope about shelling out. I am happy to implement this if you guys can give me some guidance on what you think think would be the best way to register ctag strategies. I was thinking of making it use regular ctags and have the user pass an option if they want ripper or starscope.

**Comment by Linuus** [comment]
Has anyone experimented with this yet? It would be nice to have a better tags generator for ruby.

**Comment by regedarek** [comment]
:+1:

**Comment by HaleTom** [comment]
Is there a configuration option to use `ripper-tags` until it (hopefully) becomes the default?

**Comment by tpope** [comment]
I just pushed a change to make `--languages=Ruby` the first argument, which means you can now use  a wrapper script to delegate to ripper-tags.  Here's the one I'm trying locally:

```sh
#!/bin/sh

if [ --languages=Ruby = "$1" ]; then
  gem install --conservative ripper-tags &&
    shift &&
    exec ripper-tags "$@"
fi

exec ctags-exuberant "$@"
```

Release forthcoming, but you can `rake install` in the meantime.

**Comment by tpope** [comment]
To be clear, I'm open to further improvements, such as a command line option to directly invoke ripper-tags (which could be then defaulted in `~/.gemrc`). Starscope could be handled that way too.
