### ISSUE TITLE
Question about usage with bundler

### ISSUE THREAD

**Issue by toupeira** [tpope/gem-ctags#14]
So I noticed that tags aren't generated for gems installed through bundler and stumbled over [your](https://github.com/bundler/bundler/pull/1364) [attempts](https://github.com/bundler/bundler/issues/1649) to solve this. If I understand correctly this is still/again broken in current Bundler releases, and I was wondering if you found a way to work around it?

**Comment by tpope** [comment]
https://github.com/tpope/gem-ctags/blob/master/lib/rubygems/commands/ctags_command.rb#L31-L37 is my evil but effective solution. Try reinstalling bundler to trigger it.

**Comment by toupeira** [comment]
:clap: that is indeed effective, thanks!
