### ISSUE TITLE
Please release v1.0.8

### ISSUE THREAD

**Issue by yuku-t** [tpope/gem-ctags#21]
I want to use field option added by #19 but it seems that [v1.0.7 does not include the patch](https://github.com/tpope/gem-ctags/blob/v1.0.7/lib/rubygems/commands/ctags_command.rb#L34). Could you release the next version?

**Comment by GriffinHeart** [comment]
@tpope This would be very useful :)

**Comment by tpope** [comment]
Add `--fields=+l` to `~/.ctags` instead.
