### ISSUE TITLE
[vim] - does not work for gems not installed via 'bundle install'

### ISSUE THREAD

**Issue by skamsie** [tpope/gem-ctags#23]
So let's say I have the following in my Gemfile and I install with `bundle install`:

```
source 'https://rubygems.org' 
gem 'activesupport' 
```

I generate the tags with `gem ctags`,  then edit a file in vim in the same dir as the Gemfile:

```
require 'active_support/all'
puts 1.month.ago
```

I can now do `gf` while cursor is on 'active_support' and also `<c-]>` when cursor is on 'ago'. These both work leading to the file and definition respectively.

However if I retry the same scenario, but instead of having a Gemfile, I just do 'gem install activesupport', I get:

```
E345: Can't find file "active_support/all.rb" in path
E426: tag not found: ago
```

Is there a way to make this work for a ruby file edited outside of a project, if the currently used ruby version already has that gem installed? I am using rbenv, and also have installed the plugins suggested as Vim Tips:

```
Plug 'tpope/vim-rake'
Plug 'tpope/vim-projectionist'
Plug 'tpope/vim-bundler'
Plug 'tpope/vim-rbenv'
```

Thanks

**Comment by tpope** [comment]
So the key here is the `'path'` and `'tags'` options. When you're in a bundler, project, bundler.vim alters these two options to contain the location of all gems as specified in the lock file. Outside of a bundler project, there really isn't a surefire way to figure out which gems are in use. A couple of options:

1. Just add every single gem to `'path'` and `'tags'`. This is what vim-ruby used to do. It was a borderline passable solution 10 years ago, but nowadays it's not unusual to have thousands of gems installed, and it gets unworkable fast.
2. Try to extract which gems are in use by examining the current file. If it's a single file project and all the gems are explicitly declared as `gem 'foo'`, this is probably quite doable, though you might run into trouble determining the correct gem version. If it's a multi file project or one is implicitly triggering gem loads with `require`, it's probably a lost cause.

My takeaway from this has been to use bundler as often as possible, even for small projects and scripts.

Do share if you manage to rig up anything.

**Comment by skamsie** [comment]
Got it! Thanks for explaining
