### ISSUE TITLE
ctags now uses `language` in singular rather than `languages` in plural

### ISSUE THREAD

**Issue by PauloPhagula** [tpope/gem-ctags#26]
because of using the old option in https://github.com/tpope/gem-ctags/blob/f947ed4e1f093e48d2305419475d0c9796e354b0/lib/rubygems/commands/ctags_command.rb#L22

installing gems often times shows this message
![Screenshot from 2020-04-29 20-13-15](https://user-images.githubusercontent.com/6130991/80631445-0097f280-8a56-11ea-89a2-a3c539906b2f.png)

**Comment by tpope** [comment]
Is that Exuberant ctags or something else?

**Comment by PauloPhagula** [comment]
Aha, so Emacs overrode ctags with its own and it uses `--language` only

Thanks
