### ISSUE TITLE
vim ctags not found tags in rails project

### ISSUE THREAD

**Issue by tinyfeng** [tpope/gem-ctags#27]
I have generated tags file on gem's root for my Rails project by running `gem ctags`, but when I stop the cursor in rails keywords, such as 'before_action', then I type `ctrl - ]`, it tips me "No tags found for: before_action".

By the way, ctags works normally for my project's methods and class tags.

Did I do something wrong? And what should I do?

My native language is not English, please forgive me for any mistakes.

**Comment by tpope** [comment]
You probably want to install [bundler.vim](/tpope/vim-bundler), which will set the `'tags'` option to include the tags files from your declared gem dependencies.
