### ISSUE TITLE
Weird filename generated in tags file

### ISSUE THREAD

**Issue by yyandrew** [tpope/gem-ctags#28]
Take tags for gem `activesupport-6.0.3.1` example

The tags for `html_safe` are something like:
```
$ ag html_safe tags

1230:html_safe  lib/active_support/core_ext/string/oy.rbt_safety.rb     /^  def html_safe$/;"    f       class:String
1231:html_safe? lib/active_support/core_ext/string/oy.rbt_safety.rb     /^    def html_safe?$/;" f       class:ActiveSupport.SafeBuffer
1232:html_safe? lib/active_support/core_ext/string/oy.rbt_safety.rb     /^  def html_safe?$/;"   f       class:Numeric
```
The file names are `oy.rbt_safety.rb` in tags files.It should be `output_safety.rb`.

I'm using:
```
ruby 2.7.1p83
Ctags 5.8
```

**Comment by tpope** [comment]
That's weird but since all we do is shell out to `ctags` with some rather mundane arguments, I don't think this could be gem-ctags's fault. Do report back if you discover anything enlightening.
